USE TABLE_EXERCISE_1

CREATE TABLE HOADON (
	MAHD	Nvarchar (10) NOT NULL PRIMARY KEY,
	NGAY    Datetime,	 
	MAKH	Nvarchar (5),
	TONGTG	money,	 
)

CREATE TABLE CHITIETHOADON (
	MAHD	Nvarchar (10),
	MAVT	Nvarchar (5),
	SL	int,	 
	KHUYENMAI	decimal,	 
	GIABAN	money,
	CONSTRAINT CTHD PRIMARY KEY (MAHD, MAVT),
)
--- thay đổi kiểu dữ liệu và kích thước của date và NOT NULL
ALTER TABLE KHACHHANG
ALTER COLUMN TENKH NVARCHAR (10) NOT NULL

ALTER TABLE VATTU 
ALTER COLUMN TENVT NVARCHAR NOT NULL;

--- CHECK điều kiện 
ALTER TABLE VATTU 
ADD CHECK (GIAMUA > 0);
ALTER TABLE VATTU
ADD CHECK (SLTON >=0);

--- thêm khoas ngoại cho bản 

ALTER TABLE HOADON
ADD FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH);

ALTER TABLE CHITIETHOADON
ADD FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD)

ALTER TABLE CHITIETHOADON
ADD FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT)


ALTER TABLE CHITIETHOADON
ADD CONSTRAINT SL
DEFAULT '1' FOR SL

ALTER TABLE CHITIETHOADON
ADD CHECK (SL > 0)

ALTER TABLE VATTU
ALTER COLUMN TENVT NVARCHAR (15) NOT NULL

--- thêm date to table 
INSERT INTO VATTU
VALUES (N'VT01', N'XI MANG', N'BAO', 50000, 5000);
INSERT INTO VATTU
VALUES (N'VT02', N'XI MANG', N'BAO', 50000, 5000);

--- truy vấn TABLE
SELECT *FROM VATTU
ALTER TABLE KHACHHANG
ALTER COLUMN TENKH NVARCHAR (20) 

INSERT INTO KHACHHANG
VALUES (N'KH01', N'NGUYEN THI BE', N'TAN BINH' , '08457895', 'bnt@yahoo.com')

INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, DT)
VALUES (N'KH02', N'NGUYEN THI BE', N'TAN BINH' , '08457895')

INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, EMAI)
VALUES (N'KH03', N'NGUYEN THI BE', N'TAN BINH' , 'bnt@yahoo.com')

SELECT *FROM KHACHHANG

INSERT INTO HOADON
VALUES (N'HD002', '12-05-2000',N'KH01', 82000)

ALTER TABLE HOADON
ALTER COLUMN NGAY DATE

SELECT *FROM HOADON