USE TABLE_EXERCISE_1
GO
-------------------------------------
SELECT TOP 2 * FROM HOADON
SELECT TOP 2 * FROM CHITIETHOADON

BEGIN TRANSACTION


INSERT INTO HOADON(MAHD, NGAY, MAKH)
VALUES (N'HD01', '02-12-2019', N'KH01');

COMMIT TRANSACTION 



-----------------------------
CREATE TRIGGER tr_tblDepartment
ON dbo.tblDepartment
AFTER DELETE, INSERT, UPDATE
AS
  BEGIN
    SET NOCOUNT ON
  END