USE TABLE_EXERCISE_1
GO

--- CAU 1
DELETE FROM KHACHHANG
WHERE MAKH ='KH02'

--- XOA RANG BUOO
ALTER TABLE KHACHHANG
DROP CONSTRAINT PK__KHACHHANG
--- NOTE TO WANT DELETE ONE COLUMN OR IS DELETE THEO IF

--- THIF PHAI DELETE PMIMARY KEY AND FOREIGN KEY

ALTER TABLE HOADON
DROP CONSTRAINT FK__HOADON

--- CAU 2
DELETE FROM KHACHHANG
WHERE DIACHI ='TAN BINH'

--- CAU 3
SELECT * FROM VATTU

DELETE FROM VATTU
WHERE GIAMUA < 10000;

--- CAU 4
 SELECT * FROM CHITIETHOADON

UPDATE CHITIETHOADON
SET GIABAN = GIABAN +GIABAN*0.1
WHERE MAVT = 'VT06' ;

--- CAU 5
UPDATE CHITIETHOADON
SET GIABAN = GIABAN +GIABAN*0.1
WHERE MAHD = 'HD01' ;