USE TABLE_EXERCISE_1
GO



--- CÂU 1 
SELECT
	MAKH,
	TENKH,
	DIACHI,
	DT,
	EMAI
	FROM KHACHHANG
	WHERE DT IN (
SELECT DT 
	FROM KHACHHANG
	WHERE DT = '08457895');

SELECT * FROM VATTU

--- CAU 2
SELECT MAVT , TENVT, DVT, GIAMUA
FROM VATTU
WHERE TENVT LIKE 'DA%'
AND GIAMUA < 30000;


---	CÂU 3
SELECT HOADON.MAHD , HOADON.NGAY,T.TENKH, T.MAKH, T.DIACHI, T.DIACHI  
FROM HOADON , (SELECT MAKH, DIACHI, TENKH, DT FROM KHACHHANG) AS T
WHERE HOADON.MAKH = T.MAKH
ORDER BY HOADON.NGAY;

--- CÂU 4
SELECT KHACHHANG.TENKH, KHACHHANG.DIACHI, KHACHHANG.DT
FROM KHACHHANG
WHERE KHACHHANG.MAKH IN  (SELECT MAKH FROM HOADON WHERE NGAY LIKE '2000-06%')

--- CAU 5
SELECT CHITIETHOADON.MAHD, CHITIETHOADON.MAVT , CHITIETHOADON.GIABAN , CHITIETHOADON.SL,
VT.TENVT, VT.MAVT, VT.GIAMUA,
VT.GIAMUA*CHITIETHOADON.SL AS N'GIÁ TRỊ MUA',
CHITIETHOADON.GIABAN * CHITIETHOADON.SL AS N'GIÁ TRỊ BÁN',
(CHITIETHOADON.GIABAN * CHITIETHOADON.SL )-  (VT.GIAMUA*CHITIETHOADON.SL) 
FROM CHITIETHOADON , ( SELECT MAVT, TENVT, GIAMUA FROM VATTU) AS VT
WHERE CHITIETHOADON.MAVT = VT.MAVT;

--- CAU 6
SELECT HD.MAHD, HD.NGAY, KHACHHANG.TENKH, KHACHHANG.DIACHI, HD.TONGTG
FROM KHACHHANG,(SELECT MAKH, MAHD, NGAY, TONGTG FROM HOADON
				WHERE TONGTG = (
									SELECT MIN(TONGTG) FROM HOADON
									WHERE HOADON.NGAY LIKE '2000%')) AS HD
WHERE KHACHHANG.MAKH = HD.MAKH;

--- CÂU 7
 SELECT SUM(KH.SL) AS SLMIN , KH.MAKH
FROM KHACHHANG,(SELECT CHITIETHOADON.MAHD ,CHITIETHOADON.SL, KHACHHANG.MAKH
FROM CHITIETHOADON 
INNER JOIN HOADON ON HOADON.MAHD = CHITIETHOADON.MAHD
INNER JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH) AS KH
GROUP BY KH.MAKH
ORDER BY SLMIN

SELECT MIN(TONGTG), MAHD FROM HOADON











SELECT * FROM HOADON