USE TABLE_EXERCISE_1
GO


---CÂU 1
--- ADD USE DATE TO DYNAMIC MEMORY
CREATE PROCEDURE CAPNHAT_STORED
AS
BEGIN
DECLARE CTHD_CURSOR CURSOR FOR SELECT MAHD FROM DBO.HOADON

OPEN CTHD_CURSOR
---CREATE VARIABLE STORAGE DATE CURSOR 
DECLARE @MAHD NVARCHAR(10)
--- 
FETCH NEXT FROM CTHD_CURSOR INTO @MAHD

WHILE @@FETCH_STATUS = 0
BEGIN
UPDATE HOADON
SET  TONGTG = (SELECT SUM(GIABAN) FROM CHITIETHOADON
				WHERE MAHD =  @MAHD
				GROUP BY MAHD)
WHERE HOADON.MAHD =  @MAHD
FETCH NEXT FROM CTHD_CURSOR INTO @MAHD
END

CLOSE CTHD_CURSOR
DEALLOCATE CTHD_CURSOR
END

EXEC CAPNHAT_STORED
GO
--- QUESITON 2
CREATE PROCEDURE SDT_PROC
@INPUT_SDT VARCHAR(10)
AS
BEGIN
	IF EXISTS( SELECT * FROM KHACHHANG WHERE DT = @INPUT_SDT)
		BEGIN
		PRINT N'KHÁCH HÀNG TỒN TẠI'
		END
	ELSE 
	BEGIN
	PRINT N'KHÁCH HÀNG KHÔNG TỒN TẠI'
	END 
END

EXEC SDT_PROC @INPUT_SDT = '08457895'
GO
--- QUESTION 3 
CREATE PROC TONGTIEN_PROC
@MAKH NVARCHAR(10)
AS
BEGIN
DECLARE @TONGTIEN BIGINT
 SELECT @TONGTIEN =SUM(TONGTG) FROM HOADON WHERE MAKH = @MAKH GROUP BY MAKH

PRINT @TONGTIEN

END
GO

EXEC TONGTIEN_PROC @MAKH = KH02

DROP PROC TONGTIEN_PROC
GO
--- QUESION 4 
CREATE PROC MAX_VATTU_PROC
AS
BEGIN
	DECLARE @TABLEMAX TABLE(SUMGIABAN BIGINT, MAVT2 NVARCHAR(20))
	INSERT INTO  @TABLEMAX SELECT SUM(GIABAN), MAVT FROM CHITIETHOADON
				GROUP BY MAVT 
	SELECT VATTU.TENVT, MAXVATTU.MAVT2, MAXVATTU.SUMGIABAN 
	FROM VATTU , (SELECT TOP 1 MAX(SUMGIABAN) AS SUMGIABAN,MAVT2 FROM  @TABLEMAX 
			  GROUP BY MAVT2
			  ORDER BY SUMGIABAN DESC) AS MAXVATTU
	WHERE VATTU.MAVT = MAXVATTU.MAVT2
END

EXEC MAX_VATTU_PROC




