USE TABLE_EXERCISE_1
GO

SELECT * FROM CHITIETHOADON
SELECT * FROM VATTU
GO
--- CAU 1 
--- KHI ADDDATE HOẶC UPDATE THÌ DÙNG FOR INSERT ĐỂ CHECK IN INPUT 
CREATE TRIGGER TG_VT ON CHITIETHOADON 
FOR INSERT AS
	/* SỬ ĐỤNG EXISTS ĐỂ CHECK SỰ TỒN TẠI     */
	IF EXISTS(SELECT * FROM inserted JOIN VATTU ON inserted.MAVT = VATTU.MAVT 
				WHERE VATTU.GIAMUA > inserted.GIABAN)
	BEGIN 
	PRINT N'GIA MUA PHẢI LỚN HƠIN 500'
	ROLLBACK TRANSACTION
	END
GO	


INSERT INTO CHITIETHOADON
VALUES (N'HD01', N'VT01', 5, 19, 50000000)
GO
--- CAU 2 
CREATE TRIGGER TG_HOADON ON CHITIETHOADON AFTER INSERT AS
BEGIN
UPDATE VATTU
SET SLTON = SLTON - (SELECT SL FROM inserted)
WHERE VATTU.MAVT = (SELECT MAVT FROM inserted)
END
GO
---CAU 3
CREATE TRIGGER TG_TANGTIEN ON CHITIETHOADON
FOR UPDATE AS
IF (SELECT CHITIETHOADON.GIABAN FROM CHITIETHOADON 
WHERE MAHD = 'HD001' AND MAVT = 'VT01') < (SELECT GIABAN FROM inserted)
BEGIN
	PRINT N'CẬP NHẬT GIÁ BÁN RA PHẢI LỚN HƠN'
	ROLLBACK TRANSACTION
END
GO

UPDATE CHITIETHOADON
SET GIABAN = 30000
WHERE MAHD = 'HD001'  AND MAVT = 'VT01'
GO

SELECT * FROM HOADON
SELECT * FROM CHITIETHOADON
GO
--- CÂU 4
CREATE TRIGGER TG_TONGTG 
ON CHITIETHOADON AFTER UPDATE AS
BEGIN 
UPDATE HOADON
SET TONGTG = (SELECT SUM(CHITIETHOADON.GIABAN) FROM  CHITIETHOADON, inserted
WHERE CHITIETHOADON.MAHD = inserted.MAHD 
GROUP BY CHITIETHOADON.MAHD)
WHERE HOADON.MAHD = (SELECT MAHD FROM inserted)
END
GO

