USE TABLE_EXERCISE_1
GO
--- CAU 1
CREATE FUNCTION FC_CAU1(
@MAVT1 NVARCHAR(5)
)
RETURNS INT
AS
BEGIN
DECLARE @GIAMUA INT

SELECT @GIAMUA = GIAMUA FROM VATTU WHERE MAVT = @MAVT1

RETURN  @GIAMUA;	
END
GO
 --CALL FUNCTION
SELECT DBO.FC_CAU1('VT02')
GO
--- CÂU 2
CREATE FUNCTION FC_CAU2(
@MAKH NVARCHAR(30)
)
RETURNS NVARCHAR(30)
AS
BEGIN
DECLARE @TENKH1 NVARCHAR(30)

SET @TENKH1 = (SELECT TENKH FROM KHACHHANG WHERE MAKH = @MAKH)

RETURN  @TENKH1;	
END
GO
--- CALL FUNCTION
SELECT DBO.FC_CAU2('KH01')

SELECT * FROM KHACHHANG
GO
--- CÂU 3
CREATE FUNCTION .FC_CAU3(
@MAKH NVARCHAR(5)
)
RETURNS BIGINT
AS
BEGIN
DECLARE @TONGTG BIGINT

SELECT @TONGTG =  SUM(TONGTG) FROM HOADON WHERE MAKH = @MAKH GROUP BY MAKH

RETURN @TONGTG 
END
GO

SELECT DBO.FC_CAU3('KH01')
GO

--- CAU 4
CREATE FUNCTION CF_CAU4()
RETURNS NVARCHAR(5)
AS
BEGIN
DECLARE @MAVT NVARCHAR(5)
DECLARE @TABLE_SUM_VT TABLE(SUMVT BIGINT, MAVT NVARCHAR(5))
INSERT INTO @TABLE_SUM_VT SELECT TOP 1 SUM(GIABAN) AS SUMVT,MAVT FROM CHITIETHOADON
							GROUP BY MAVT
							ORDER BY SUMVT DESC

SELECT @MAVT = MAVT FROM @TABLE_SUM_VT
	
RETURN @MAVT;
END
GO

SELECT DBO.CF_CAU4()
GO
DROP FUNCTION CF_CAU4



