USE TABLE_EXERCISE_1
GO

--- INNER JOIN TWO TABLE 
--- CỨ PHÁP SELECT CỘT CẦN HIÊN THỊ 
--- TABLE 1
--- INNER JOIN TABLE ĐƯỢC LIÊN KẾT
--- ON ĐIỆU KIỂN LIÊN KẾT
--- CÂU 1
SELECT HOADON.MAHD, HOADON.NGAY, KHACHHANG.TENKH, KHACHHANG.DIACHI, KHACHHANG.DT 
FROM HOADON
INNER JOIN KHACHHANG 
ON HOADON.MAKH = KHACHHANG.MAKH;
---CÂU 2
SELECT HOADON.MAHD, KHACHHANG.TENKH, KHACHHANG.DIACHI, KHACHHANG.DT
FROM HOADON
INNER JOIN KHACHHANG
ON HOADON.MAKH = KHACHHANG.MAKH
WHERE NGAY = '2000-05-25';


--- CÂU 3
SELECT HOADON.MAHD , HOADON.NGAY ,KHACHHANG.TENKH , KHACHHANG.DIACHI, KHACHHANG.DT
FROM HOADON
INNER JOIN KHACHHANG
ON HOADON.MAKH = KHACHHANG.MAKH
WHERE NGAY LIKE '2000-06%';

--- CÂU 4
SELECT KHACHHANG.TENKH , KHACHHANG.DIACHI, KHACHHANG.DT
FROM KHACHHANG
INNER JOIN HOADON
ON HOADON.MAKH = KHACHHANG.MAKH
WHERE NGAY LIKE '2000-06%';

---CÂU 5
SELECT VATTU.MAVT ,VATTU.TENVT
FROM HOADON
INNER JOIN CHITIETHOADON ON  CHITIETHOADON.MAHD = HOADON.MAHD
INNER JOIN VATTU ON VATTU.MAVT = CHITIETHOADON.MAVT
WHERE NGAY BETWEEN '2000-01-01' AND '2000-07-12';




---CÂU 6
SELECT VATTU.MAVT ,VATTU.TENVT, KHACHHANG.TENKH
FROM HOADON
INNER JOIN CHITIETHOADON ON  CHITIETHOADON.MAHD = HOADON.MAHD
INNER JOIN VATTU ON VATTU.MAVT = CHITIETHOADON.MAVT
INNER JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE NGAY BETWEEN '2000-01-01' AND '2000-07-12';

--- CÂU 7
SELECT VATTU.MAVT ,VATTU.TENVT, KHACHHANG.TENKH,HOADON.NGAY, CHITIETHOADON.SL
FROM (((KHACHHANG
INNER JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH)
INNER JOIN CHITIETHOADON ON CHITIETHOADON.MAHD = HOADON.MAHD)
INNER JOIN VATTU ON VATTU.MAVT = CHITIETHOADON.MAVT)
WHERE DIACHI = 'TAN BINH' AND NGAY LIKE '2000%';

---CÂU 8 TƯƠNG TỰ CÂU 7
--- CÂU 9 
SELECT DISTINCT KHACHHANG.TENKH, KHACHHANG.DIACHI, KHACHHANG.DT
FROM HOADON
INNER JOIN KHACHHANG ON KHACHHANG.MAKH = HOADON.MAKH
WHERE NGAY NOT LIKE '2000-06%';


SELECT *FROM KHACHHANG 
SELECT *FROM HOADON
SELECT *FROM CHITIETHOADON