	USE TABLE_EXERCISE_1

	GO
	ALTER TABLE CHITIETHOADON
	DROP CONSTRAINT CTHD;

	SELECT * FROM KHACHHANG
	
	--- QUERY CÓ ĐIỆU KIỂN 
	SELECT * FROM KHACHHANG
	WHERE DIACHI = 'TAN BINH';

	--- display column is DT and EMAIL not pan
	SELECT *FROM KHACHHANG
	WHERE NOT DT ='NULL' AND NOT EMAI = 'NULL';

	--- show column theo if
	SELECT MAVT, DVT, GIAMUA  FROM VATTU

	SELECT MAVT, DVT, GIAMUA  FROM VATTU
	WHERE GIAMUA >= 20000 AND GIAMUA <= 40000;

	INSERT INTO CHITIETHOADON
	VALUES (N'HD001', N'VT01' , 5, 18, 52000 )

	INSERT INTO CHITIETHOADON
	VALUES (N'HD001', N'VT01' , 5, 18, 52000 )

	INSERT INTO CHITIETHOADON
	VALUES (N'HD002', N'VT01' , 5, 18, 52000 )

	INSERT INTO CHITIETHOADON
	VALUES (N'HD002', N'VT02' , 1, 18, 50000 )

	
	SELECT  MAHD,COUNT(MAVT) AS LOAIVATTU
	FROM CHITIETHOADON
	GROUP BY MAHD;

	SELECT MAHD , SUM(SL * GIABAN) 
	FROM CHITIETHOADON
	GROUP BY MAHD;
	
	
	